


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."request_approval_status" AS ENUM (
    'Approved',
    'Denied',
    'Pending',
    'Unreviewed'
);


ALTER TYPE "public"."request_approval_status" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."can_review_requests"() RETURNS boolean
    LANGUAGE "sql" STABLE
    SET "search_path" TO 'public', 'pg_temp'
    AS $$
  select public.current_role_id() in (1,3)
$$;


ALTER FUNCTION "public"."can_review_requests"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."current_account_id"() RETURNS bigint
    LANGUAGE "sql" STABLE
    SET "search_path" TO 'public', 'pg_temp'
    AS $$
  select a.id
  from public.account a
  where a.supabase_uid = public.current_uid()
  limit 1
$$;


ALTER FUNCTION "public"."current_account_id"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."current_auth_role"() RETURNS "text"
    LANGUAGE "sql" STABLE
    SET "search_path" TO 'public', 'pg_temp'
    AS $$
  select auth.role()
$$;


ALTER FUNCTION "public"."current_auth_role"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."current_role_id"() RETURNS bigint
    LANGUAGE "sql" STABLE
    SET "search_path" TO 'public', 'pg_temp'
    AS $$
  select a.role_id
  from public.account a
  where a.supabase_uid = public.current_uid()
  limit 1
$$;


ALTER FUNCTION "public"."current_role_id"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."current_uid"() RETURNS "uuid"
    LANGUAGE "sql" STABLE
    SET "search_path" TO 'public', 'pg_temp'
    AS $$
  select auth.uid()
$$;


ALTER FUNCTION "public"."current_uid"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."is_admin"() RETURNS boolean
    LANGUAGE "sql" STABLE
    SET "search_path" TO 'public', 'pg_temp'
    AS $$
  select public.current_role_id() = 1
$$;


ALTER FUNCTION "public"."is_admin"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."is_staff"() RETURNS boolean
    LANGUAGE "sql" STABLE
    SET "search_path" TO 'public', 'pg_temp'
    AS $$
  select public.current_role_id() in (1,2,3,4)
$$;


ALTER FUNCTION "public"."is_staff"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."account" (
    "id" bigint NOT NULL,
    "role_id" bigint NOT NULL,
    "settings_id" bigint NOT NULL,
    "username" "text" NOT NULL,
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "email" "text",
    "phone" "text",
    "supabase_uid" "uuid" NOT NULL,
    "driver_status" "text" DEFAULT 'offline'::"text" NOT NULL,
    "last_seen" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "account_driver_status_check" CHECK (("driver_status" = ANY (ARRAY['available'::"text", 'assigned'::"text", 'offline'::"text"])))
);


ALTER TABLE "public"."account" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."account_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."account_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."account_id_seq" OWNED BY "public"."account"."id";



CREATE TABLE IF NOT EXISTS "public"."audit_log" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "body" "text" NOT NULL
);


ALTER TABLE "public"."audit_log" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."audit_log_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."audit_log_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."audit_log_id_seq" OWNED BY "public"."audit_log"."id";



CREATE TABLE IF NOT EXISTS "public"."cookie" (
    "id" bigint NOT NULL,
    "account" bigint NOT NULL,
    "cookie" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "expires" timestamp without time zone DEFAULT ("now"() + '7 days'::interval) NOT NULL
);


ALTER TABLE "public"."cookie" OWNER TO "postgres";


ALTER TABLE "public"."cookie" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."cookie_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."house" (
    "id" bigint NOT NULL,
    "account_id" bigint,
    "address" "text" NOT NULL,
    "supabase_uid" "uuid"
);


ALTER TABLE "public"."house" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."house_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."house_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."house_id_seq" OWNED BY "public"."house"."id";



CREATE TABLE IF NOT EXISTS "public"."notification" (
    "id" bigint NOT NULL,
    "recipient" bigint NOT NULL,
    "title" "text" NOT NULL,
    "body" "text" NOT NULL
);


ALTER TABLE "public"."notification" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."notification_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."notification_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."notification_id_seq" OWNED BY "public"."notification"."id";



CREATE TABLE IF NOT EXISTS "public"."request" (
    "id" bigint NOT NULL,
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "house_id" bigint NOT NULL,
    "email" "text",
    "phone" "text",
    "transport_id" bigint,
    "source_address" "text" NOT NULL,
    "destination_address" "text" NOT NULL,
    "requested_pickup_time" timestamp with time zone NOT NULL,
    "requested_dropoff_time" timestamp with time zone NOT NULL,
    "request_comment" "text",
    "reviewed_by" bigint,
    "reviewed_at" timestamp with time zone,
    "approved" "public"."request_approval_status" DEFAULT 'Unreviewed'::"public"."request_approval_status" NOT NULL,
    "approval_comment" "text"
);


ALTER TABLE "public"."request" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."request_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."request_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."request_id_seq" OWNED BY "public"."request"."id";



CREATE TABLE IF NOT EXISTS "public"."role" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text" NOT NULL
);


ALTER TABLE "public"."role" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."role_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."role_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."role_id_seq" OWNED BY "public"."role"."id";



CREATE TABLE IF NOT EXISTS "public"."transport" (
    "id" bigint NOT NULL,
    "staff_id" bigint NOT NULL,
    "pickup_time" timestamp with time zone,
    "dropoff_time" timestamp with time zone,
    "miles_driven" integer,
    "vehicle" bigint
);


ALTER TABLE "public"."transport" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."transport_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."transport_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."transport_id_seq" OWNED BY "public"."transport"."id";



CREATE TABLE IF NOT EXISTS "public"."user_settings" (
    "id" bigint NOT NULL
);


ALTER TABLE "public"."user_settings" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."user_settings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."user_settings_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."user_settings_id_seq" OWNED BY "public"."user_settings"."id";



ALTER TABLE ONLY "public"."account" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."account_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."audit_log" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."audit_log_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."house" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."house_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."notification" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."notification_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."request" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."request_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."role" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."role_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."transport" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."transport_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."user_settings" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."user_settings_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."audit_log"
    ADD CONSTRAINT "audit_log_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."cookie"
    ADD CONSTRAINT "cookie_cookie_key" UNIQUE ("cookie");



ALTER TABLE ONLY "public"."cookie"
    ADD CONSTRAINT "cookie_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."house"
    ADD CONSTRAINT "house_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."house"
    ADD CONSTRAINT "house_supabase_uid_key" UNIQUE ("supabase_uid");



ALTER TABLE ONLY "public"."notification"
    ADD CONSTRAINT "notification_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."request"
    ADD CONSTRAINT "request_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."role"
    ADD CONSTRAINT "role_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."account"
    ADD CONSTRAINT "staff_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."account"
    ADD CONSTRAINT "staff_supabase_uid_key" UNIQUE ("supabase_uid");



ALTER TABLE ONLY "public"."transport"
    ADD CONSTRAINT "transport_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."account"
    ADD CONSTRAINT "unique_username" UNIQUE ("username");



ALTER TABLE ONLY "public"."user_settings"
    ADD CONSTRAINT "user_settings_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_account_driver_status" ON "public"."account" USING "btree" ("driver_status");



CREATE INDEX "idx_account_supabase_uid" ON "public"."account" USING "btree" ("supabase_uid");



CREATE INDEX "idx_house_account_id" ON "public"."house" USING "btree" ("account_id");



CREATE INDEX "idx_notification_recipient" ON "public"."notification" USING "btree" ("recipient");



CREATE INDEX "idx_request_house_id" ON "public"."request" USING "btree" ("house_id");



CREATE INDEX "idx_request_transport_id" ON "public"."request" USING "btree" ("transport_id");



CREATE INDEX "idx_transport_staff_id" ON "public"."transport" USING "btree" ("staff_id");



ALTER TABLE ONLY "public"."cookie"
    ADD CONSTRAINT "cookie_account_fkey" FOREIGN KEY ("account") REFERENCES "public"."account"("id");



ALTER TABLE ONLY "public"."notification"
    ADD CONSTRAINT "fk_notification_staff" FOREIGN KEY ("recipient") REFERENCES "public"."account"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."request"
    ADD CONSTRAINT "fk_request_reviewed_by" FOREIGN KEY ("reviewed_by") REFERENCES "public"."account"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."request"
    ADD CONSTRAINT "fk_request_transport" FOREIGN KEY ("transport_id") REFERENCES "public"."transport"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."account"
    ADD CONSTRAINT "fk_staff_role" FOREIGN KEY ("role_id") REFERENCES "public"."role"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."account"
    ADD CONSTRAINT "fk_staff_settings" FOREIGN KEY ("settings_id") REFERENCES "public"."user_settings"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."transport"
    ADD CONSTRAINT "fk_transport_staff" FOREIGN KEY ("staff_id") REFERENCES "public"."account"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."house"
    ADD CONSTRAINT "house_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id");



ALTER TABLE ONLY "public"."request"
    ADD CONSTRAINT "request_house_id_fkey" FOREIGN KEY ("house_id") REFERENCES "public"."house"("id");



ALTER TABLE "public"."account" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "account: select" ON "public"."account" FOR SELECT TO "authenticated" USING ((("supabase_uid" = "public"."current_uid"()) OR "public"."is_admin"()));



CREATE POLICY "account: update" ON "public"."account" FOR UPDATE TO "authenticated" USING (("supabase_uid" = "public"."current_uid"())) WITH CHECK (("supabase_uid" = "public"."current_uid"()));



ALTER TABLE "public"."audit_log" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "audit_log: admin all" ON "public"."audit_log" TO "authenticated" USING ("public"."is_admin"()) WITH CHECK ("public"."is_admin"());



ALTER TABLE "public"."cookie" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."house" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "house: delete" ON "public"."house" FOR DELETE TO "authenticated" USING ("public"."is_admin"());



CREATE POLICY "house: insert" ON "public"."house" FOR INSERT TO "authenticated" WITH CHECK (("public"."is_admin"() OR ("account_id" = "public"."current_account_id"())));



CREATE POLICY "house: select" ON "public"."house" FOR SELECT TO "authenticated" USING ((("account_id" = "public"."current_account_id"()) OR "public"."is_admin"()));



CREATE POLICY "house: update" ON "public"."house" FOR UPDATE TO "authenticated" USING (("public"."is_admin"() OR ("account_id" = "public"."current_account_id"()))) WITH CHECK (("public"."is_admin"() OR ("account_id" = "public"."current_account_id"())));



ALTER TABLE "public"."notification" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "notification: delete" ON "public"."notification" FOR DELETE TO "authenticated" USING ("public"."is_admin"());



CREATE POLICY "notification: insert" ON "public"."notification" FOR INSERT TO "authenticated" WITH CHECK ("public"."is_admin"());



CREATE POLICY "notification: select" ON "public"."notification" FOR SELECT TO "authenticated" USING ((("recipient" = "public"."current_account_id"()) OR "public"."is_admin"()));



CREATE POLICY "notification: update" ON "public"."notification" FOR UPDATE TO "authenticated" USING ("public"."is_admin"()) WITH CHECK ("public"."is_admin"());



ALTER TABLE "public"."request" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "request: delete" ON "public"."request" FOR DELETE TO "authenticated" USING ("public"."is_admin"());



CREATE POLICY "request: insert" ON "public"."request" FOR INSERT WITH CHECK (((("public"."current_auth_role"() = 'anon'::"text") AND ("first_name" IS NOT NULL) AND ("length"(TRIM(BOTH FROM "first_name")) > 0) AND ("last_name" IS NOT NULL) AND ("length"(TRIM(BOTH FROM "last_name")) > 0) AND ("source_address" IS NOT NULL) AND ("length"(TRIM(BOTH FROM "source_address")) > 0) AND ("destination_address" IS NOT NULL) AND ("length"(TRIM(BOTH FROM "destination_address")) > 0) AND ("requested_pickup_time" IS NOT NULL) AND ("requested_dropoff_time" IS NOT NULL)) OR (("public"."current_auth_role"() = 'authenticated'::"text") AND ("public"."is_staff"() OR (EXISTS ( SELECT 1
   FROM "public"."house" "h"
  WHERE (("h"."id" = "request"."house_id") AND ("h"."account_id" = "public"."current_account_id"()))))))));



CREATE POLICY "request: select" ON "public"."request" FOR SELECT TO "authenticated" USING (("public"."is_staff"() OR (EXISTS ( SELECT 1
   FROM "public"."house" "h"
  WHERE (("h"."id" = "request"."house_id") AND ("h"."account_id" = "public"."current_account_id"()))))));



CREATE POLICY "request: update" ON "public"."request" FOR UPDATE TO "authenticated" USING ("public"."can_review_requests"()) WITH CHECK ("public"."can_review_requests"());



ALTER TABLE "public"."role" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."transport" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "transport: delete" ON "public"."transport" FOR DELETE TO "authenticated" USING ("public"."is_admin"());



CREATE POLICY "transport: insert" ON "public"."transport" FOR INSERT TO "authenticated" WITH CHECK ("public"."is_admin"());



CREATE POLICY "transport: select" ON "public"."transport" FOR SELECT TO "authenticated" USING ("public"."is_staff"());



CREATE POLICY "transport: update" ON "public"."transport" FOR UPDATE TO "authenticated" USING (("public"."is_admin"() OR ("staff_id" = "public"."current_account_id"()))) WITH CHECK (("public"."is_admin"() OR ("staff_id" = "public"."current_account_id"())));



ALTER TABLE "public"."user_settings" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."can_review_requests"() TO "anon";
GRANT ALL ON FUNCTION "public"."can_review_requests"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."can_review_requests"() TO "service_role";



GRANT ALL ON FUNCTION "public"."current_account_id"() TO "anon";
GRANT ALL ON FUNCTION "public"."current_account_id"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."current_account_id"() TO "service_role";



GRANT ALL ON FUNCTION "public"."current_auth_role"() TO "anon";
GRANT ALL ON FUNCTION "public"."current_auth_role"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."current_auth_role"() TO "service_role";



GRANT ALL ON FUNCTION "public"."current_role_id"() TO "anon";
GRANT ALL ON FUNCTION "public"."current_role_id"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."current_role_id"() TO "service_role";



GRANT ALL ON FUNCTION "public"."current_uid"() TO "anon";
GRANT ALL ON FUNCTION "public"."current_uid"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."current_uid"() TO "service_role";



GRANT ALL ON FUNCTION "public"."is_admin"() TO "anon";
GRANT ALL ON FUNCTION "public"."is_admin"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_admin"() TO "service_role";



GRANT ALL ON FUNCTION "public"."is_staff"() TO "anon";
GRANT ALL ON FUNCTION "public"."is_staff"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_staff"() TO "service_role";


















GRANT ALL ON TABLE "public"."account" TO "anon";
GRANT ALL ON TABLE "public"."account" TO "authenticated";
GRANT ALL ON TABLE "public"."account" TO "service_role";



GRANT ALL ON SEQUENCE "public"."account_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."account_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."account_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."audit_log" TO "anon";
GRANT ALL ON TABLE "public"."audit_log" TO "authenticated";
GRANT ALL ON TABLE "public"."audit_log" TO "service_role";



GRANT ALL ON SEQUENCE "public"."audit_log_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."audit_log_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."audit_log_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."cookie" TO "anon";
GRANT ALL ON TABLE "public"."cookie" TO "authenticated";
GRANT ALL ON TABLE "public"."cookie" TO "service_role";



GRANT ALL ON SEQUENCE "public"."cookie_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."cookie_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."cookie_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."house" TO "anon";
GRANT ALL ON TABLE "public"."house" TO "authenticated";
GRANT ALL ON TABLE "public"."house" TO "service_role";



GRANT ALL ON SEQUENCE "public"."house_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."house_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."house_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."notification" TO "anon";
GRANT ALL ON TABLE "public"."notification" TO "authenticated";
GRANT ALL ON TABLE "public"."notification" TO "service_role";



GRANT ALL ON SEQUENCE "public"."notification_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."notification_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."notification_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."request" TO "anon";
GRANT ALL ON TABLE "public"."request" TO "authenticated";
GRANT ALL ON TABLE "public"."request" TO "service_role";



GRANT ALL ON SEQUENCE "public"."request_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."request_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."request_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."role" TO "anon";
GRANT ALL ON TABLE "public"."role" TO "authenticated";
GRANT ALL ON TABLE "public"."role" TO "service_role";



GRANT ALL ON SEQUENCE "public"."role_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."role_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."role_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."transport" TO "anon";
GRANT ALL ON TABLE "public"."transport" TO "authenticated";
GRANT ALL ON TABLE "public"."transport" TO "service_role";



GRANT ALL ON SEQUENCE "public"."transport_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."transport_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."transport_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."user_settings" TO "anon";
GRANT ALL ON TABLE "public"."user_settings" TO "authenticated";
GRANT ALL ON TABLE "public"."user_settings" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_settings_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_settings_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_settings_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


